// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Beu7mgmvEPtv78kV-1_RMtoS2SUC8nI',
    appId: '1:497704262761:android:bb578112e616ff3dc596f8',
    messagingSenderId: '497704262761',
    projectId: 'chat-a89a0',
    storageBucket: 'chat-a89a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCG2OOIsB7rlZLvzbEqMkjwNS5hpqsmoU',
    appId: '1:497704262761:ios:42d245207bfc0aa1c596f8',
    messagingSenderId: '497704262761',
    projectId: 'chat-a89a0',
    storageBucket: 'chat-a89a0.appspot.com',
    androidClientId: '497704262761-gikmvd0neb1uuukse9rr6a7bl31cevut.apps.googleusercontent.com',
    iosClientId: '497704262761-bokmud2hmk5v4hb1ps897bvs8vvt29eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
